### ISSUE TITLE
multiple installed kernel version error

### ISSUE THREAD

**Issue by d-a-v** [ofhellsfire/ubuntu-old-kernel-purger#2]
Hello,

This is the error message I get :

"Extracted installed major version: 3.2.0 doesn't match against current version: 3.13.0"

I indeed have a kernel 3.2 installed while I'm running 3.13.0-51 and have 3.13.0-53 installed.
I have not rebooted yet since 31 days (and a lot of servers don't reboot unless forced).
My wishes is to have, after your script execution:
- the latest 3.2 kept (3.2.0-70)
- the latest 3.13 kept (3.13.0-53)
  (= the latest version of any major version found)
- the current/running kept 3.13.0-51
- all the other gone (I have 3.13.0-39 through -53 installed)

Is this a good way of purging kernel ?
Do you think it is worth updating your script to do so ?

Thanks

**Comment by ofhellsfire** [comment]
Hi,

I'll check your case as soon as possible. Probably there is a bug in the script. Speaking of inhancements I'd like to thank you for your feedback and your preferences. I'll take it into account when back to fix the issue.

Thanks again

**Comment by ofhellsfire** [comment]
This issue has been fixed with 0.1 tag. Now it is possible to specify kernel versions to be kept in a .kernelkeep file (specify every kernel version to be kept in the separate line), so those versions will be excluded from purging. Yes, it requires a bit of configuration, however having it this issue is considered as fixed. Thx.
